sudo:       required
services:   docker
# Below is GH_TOKEN:
# github -> personal access token
# gem install travis
# travis encrypt --add (<- interactive)
# GH_TOKEN=thetokengoeshere
env:
  global:
    secure: GITHUBTOKEN-SECURE

script:
  - docker pull strauman/travis-latexbuild
  - docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild
  - [ -f travis/push.sh ] && . .travis/push.sh
