sudo:       required
language:   generic
services:   docker

tex-config:
- tex-scheme=small
- push-type=none
- build-pattern=tests/*/main.tex,moretst/multiplepath.tex
- packages=lipsum, blindtext

script:
- docker run --mount src=$TRAVIS_BUILD_DIR/,target=/repo,type=bind strauman/travis-latexbuild:small # Select small TeX Live scheme